### ISSUE TITLE
Google is shutting down openid. - Support for Google OAuth2 ?

### ISSUE THREAD

**Issue by Shusshu** [SonarQubeCommunity/sonar-openid#4]
https://developers.google.com/+/api/auth-migration#timetable

**Comment by jmcazaux** [comment]
I am interested as well!

There is a similar question in the mailing list as well (http://sonar.markmail.org/thread/4fecry6kn5vcjc4s), but the topic does not seem to be on anyone's radar.

Is there an alternative?

Google login is really a plus when using Google apps...

**Comment by Xeli** [comment]
Did you find any alternatives for this?

**Comment by Shusshu** [comment]
This is the alternative:
https://wiki.jenkins-ci.org/display/JENKINS/Google+Login+Plugin



Benoit Billington

**Comment by jmcazaux** [comment]
@Xeli Indeed this is what I ended up using.

**Comment by Xeli** [comment]
How do you use that with sonar though?

**Comment by Shusshu** [comment]
my bad ;)

**Comment by sebglon** [comment]
+1

**Comment by bellingard** [comment]
Guys, FYI, we are planning to add OAuth support in SQ => http://jira.sonarsource.com/browse/SONAR-6226

**Comment by simonbrandhof** [comment]
I close this ticket as multiple Google OAuth2 plugins exist for SonarQube 5.6: http://docs.sonarqube.org/display/PLUG/Other+Plugins
