### ISSUE TITLE
Restricted gapps domain support

### ISSUE THREAD

**Issue by bellingard** [SonarQubeCommunity/sonar-openid#7]
(coming from http://jira.sonarsource.com/browse/SONAROPNID-11)

Ability to restrict the Google OpenID to particular domains. Two new configuration properties:
```
sonar.openid.google.domain=lashpoint.com
# optional, defaults to the below value
sonar.openid.google.endpoint=https://www.google.com/accounts/o8/site-xrds?hd=
```
See pull request https://github.com/SonarCommunity/sonar-openid/pull/1

**Comment by simonbrandhof** [comment]
Google does not support OpenID anymore
